description: 
    <div class="tabs-container">
        <a href="./lesungen.html" class="tab">Lesungen</a>
        <a href="./maerchen.html" class="tab">Märchen</a>
        <a href="./trommeln.html" class="tab">Trommelworkshop</a>
        <a href="./about.html" class="tab">Kontakt</a>
    </div>

# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false

theme: jekyll-theme-cayman
