description: <a href="./lesungen.html" class="btn">Lesungen</a>
        <a href="./maerchen.html" class="btn">Märchen</a>
        <a href="./trommeln.html" class="btn">Trommelworkshop</a>
        <a href="./about.html" class="btn">Kontakt</a>

# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false

theme: jekyll-theme-cayman
